### ISSUE TITLE
TeamCity reporter

### ISSUE THREAD

**Issue by shuhrat** [gemini-testing/gemini#106]
Please, revert 7b25c3390c48581baa10a2037f3e1311511fb60a
We use TeamCity reporter, and I am ready to maintain it, if there would any API changes.
At least provide ability to load reporters from external packages.

//cc @anton-rudeshko @mishanga

**Comment by SevInf** [comment]
The code in 7b25c33 won't work anymore – it was a primary reason for removal. When we implemented `grep` option (#62) we found out that TeamCity reporter and new option does not play very nicely together. Since we never actually used this reporter, we decided to remove it, instead of fixing. 

But if you'll provide a PR with a restored TeamCity reporter I will happily merge it.

**Comment by anton-rudeshko** [comment]
Perhaps it would be better to move it to separate repo?

**Comment by shuhrat** [comment]
Plug-in support was added, will use https://github.com/Saulis/gemini-teamcity
Thank you!
