### ISSUE TITLE
[enhancement] Diff the reference directory and another directory without executing suites

### ISSUE THREAD

**Issue by czintl** [gemini-testing/gemini#157]
We have a bunch of Selenium-Tests already, to check a couple of our web-applications, so we could just add "take snapshot" to the existing code and then diff them with gemini. The directories could follow the same structure as if they came from gemini-suites, that would be just fine.

There are also 1 or 2 applications where we need the full functionality.
It would be great to be able to use both, the flat reporter and the html reporter in both cases, so we can neatly integrate both methods in our build-process and have the same look-and-feel for both.

Something like:

    gemini compare --reporter flat --reporter html /reference_directory /snapshot_directory

I already had a look at the code, and tried to implement it myself, but I have too little experience with nodejs and esp. debugging multithreaded nodejs to be able to do that in due time.

It would be nice to see someone do that, or give me some context on how to implement it, then I'd do it and make a pull-request (but remember, I'm a nodejs noob ;-) )

**Comment by SevInf** [comment]
Sorry for the late response.
I don't think this functionality should be available in the core, but its a perfect fit for a plugin or external tool using the API.
One of the ways it can be implemented is dropping gemini entirely for the first case and just using [`looks-same`](https://github.com/gemini-testing/looks-same). All gemini image comparsion logic is there and you can get the same result gemini would give you, but use your own images. If your tests are written in JS you can use it as a library, if they are in some other language you can just implement simple executable in `node.js` and use it. For me it looks like the best way to solve your problem.

Another way to achieve what you want may be subclassing [`CaptureSession`](https://github.com/gemini-testing/gemini/blob/master/lib/capture-session.js) class. You'll need to:
1. Replace [`runHook`](https://github.com/gemini-testing/gemini/blob/master/lib/capture-session.js#L20-L29) method with noop.
2. Instead of [this code](https://github.com/gemini-testing/gemini/blob/master/lib/capture-session.js#L37-L55) just read image from disk.
3. Move [this call](https://github.com/gemini-testing/gemini/blob/master/lib/runner.js#L132) to session class and replace it with noop for you subclass.
4. Use either current session implementation or your subclass in `runner.js` depending on some option or command-line flag.
But generally, I would like to recommend you to try first approach and see if it works for you before diving into the second one.
