### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by newtonianb** [gemini-testing/gemini#199]
First of all, this tool is incredible thanks so much for it. Also installation went pretty smoothly so great job on that too.

Lastly though I'm a bit surprised with the performance I'm getting, it feel a bit too slow on my test. I ran a simple test

```
var gemini = require('gemini');

gemini.suite('header', function(suite) {
    suite.setUrl('/')
        .setCaptureElements(['.myHeader .container-fluid'])
        .capture('plain');
});
```

And it seems to take 14 seconds to run and that's just one test! At this speed I just can't really use this. The screenshot taken is 8.41kb, it represents a region that's roughly 100 px high.

What's the bottle neck here? Note: I am using phantomjs webdriver...

**Comment by SevInf** [comment]
Most of this 14 seconds in your tests are browser startup time and calibration. It won't take 14 seconds to run all of the tests — just the first one, because by default, gemini launches each browser only once for all tests and once and then reuses it. You can speed up startup time a bit by disabling calibration: here are the instructions for [0.12](https://github.com/gemini-testing/gemini/blob/stable/doc/config.md)(`--noCalibrate` capability) and [0.13](https://github.com/gemini-testing/gemini/blob/master/doc/config.md#browsers-settings) (`calibrate` option).

**Comment by newtonianb** [comment]
@SevInf thanks for this information. If I understand correctly calibrate is only needed if you want isolated screenshots in the results is that right?

**Comment by SevInf** [comment]
@newtonianb calibration is needed to correctly deal with WebDriver implementations that do not take screenshot as the spec requires (i.e. capture browser UI along with the content of the page). For phantom it can be safely disabled, as their implementation is comply with a spec.

**Comment by newtonianb** [comment]
Thank you
