### ISSUE TITLE
Remove bundleDependencies from package.json

### ISSUE THREAD

**Issue by sipayRT** [gemini-testing/gemini#322]
@SevInf why do we need it?

**Comment by SevInf** [comment]
The rational is explained in 13ced8a4197e52b801b1f394c55056e02bf99ef5.
The main reason is this libraries, unlike `q` or `lodash` provide core functionality of gemini. If `looks-same` changes the way it compares the images, `gemini` changes the way it compares the images. If a bug about incorrect config parsing is reported in `gemini` user expects it to be fixed in a new version, not by reinstalling the same version.

**Comment by sipayRT** [comment]
ok, tnx for the explanation
