### ISSUE TITLE
Simulate user login

### ISSUE THREAD

**Issue by geitsund** [gemini-testing/gemini#354]
I'm writing a test for a web page that requires login. The login is done through a windows login dialog (ref. image).

I have done login from a web form, but i can't find a way to send keys and do a click in a dialog window like this.

Any help would be much appreciated.

![image](https://cloud.githubusercontent.com/assets/6672239/12353883/5913857e-bb92-11e5-9f8c-c0561a00127a.png)

**Comment by SwinX** [comment]
Hi @geitsund, thanks for the report.

Am I right that this login form is not a part of a web page? In this case it seems to be something what gemini can't handle because it controls only browser, not any environment. 
Seems that good decision for you may be stubbing code which invokes this dialog and proceed to actual web page directly.

**Comment by SwinX** [comment]
@geitsund is this still actual?

**Comment by geitsund** [comment]
@SwinX No, we managed to solve it on our side.
