### ISSUE TITLE
Add sample test case file name to documentation.

### ISSUE THREAD

**Issue by CharlesBelov** [gemini-testing/gemini#380]
The quick start documentation gives a file name, including extension, .gemini.yml for the configuration file. However, there is no sample file name provided for the test case. Please provide one, including extension.

**Comment by CharlesBelov** [comment]
It would also be nice to mention that test cases are written in JavaScript.

**Comment by SwinX** [comment]
@CharlesBelov test file name depends on what you test. For instance if you're testing button then good name for file with tests will be `button.gemini.js`
Name for config provided not because it's recommended name but because this is default name and gemini will look for it if it's not redefined somehow.
