### ISSUE TITLE
Compare screenshots of Browser-A with Browser-B

### ISSUE THREAD

**Issue by Purus** [gemini-testing/gemini#388]
Gemini does a great job of comparing images of same browser using Selenium Grid.

Is it possible to compare screenshots of chrome with Firefox and IE to find any layout issues?

I could not see any docs for the same.

**Comment by sipayRT** [comment]
Gemini can't do it. If I understood correctly you need to check pixel-perfect layout. In this case you need to make screenshot from one browser and duplicate it with different names. But I don't believe that it makes sense - you will got many diff because of different of the browser's rendering.

**Comment by Purus** [comment]
Exactly that's the point. It will help us to automatically find any major layout differences.

We can use image difference tools and set some variance to highlight only major differences.

**Comment by SwinX** [comment]
@Purus the problem here is what exactly is major difference. For example there is pretty big difference in font rendering among different browsers - all have a little bit different font inside, someone may use not exactly what you requested and as result you will see huge red areas on diff image. Also because of slightly different actual font heights in resulting page render all elements will be moved for a bit.
And this is only one case related to fonts. There are much more if look deeper. Because of this issues gemini was designed to check layout for each browser separately.
If you need to check the final page layout in general maybe it will be a good idea to have tests for templates and check what they produce.
