### ISSUE TITLE
Zombie support?

### ISSUE THREAD

**Issue by stevenvachon** [gemini-testing/gemini#572]

**Comment by sipayRT** [comment]
![](http://img.playground.ru/images/1/3/WAT.jpg)

what do you mean?

**Comment by stevenvachon** [comment]
I'm asking for [zombie](https://npmjs.com/zombie) support. Some might prefer to use it over a real/headless browser.

**Comment by sipayRT** [comment]
Sorry, only phantomjs supported now

**Comment by stevenvachon** [comment]
This was a feature request.

**Comment by SevInf** [comment]
Just a little clarification: 
The only thing which gemini really supports is WebDriver protocol. You won't find any "PhantomJS support" or "Real browsers support" code inside: they all work through the same protocol. 
Moreover, in order to test the appearence, the underlying engine should be capable of, well, image rendering. Correct me if I wrong, but Zombie.js does not provide such functionality. 

So, unless Zombie.js implements: 
- rendering 
- web driver protocol 

there is nothing we can really do to support it.

**Comment by stevenvachon** [comment]
Zombie.js may get it in the future. [zombiecss](https://npmjs.com/zombiecss) was working at one point.

**Comment by stevenvachon** [comment]
However, having gotten my hands into Zombie and Nightmare, I don't see much use in supporting Zombie or even Electron as we could use those in place of this module.
