### ISSUE TITLE
Overwriting configuration from cli does not work

### ISSUE THREAD

**Issue by gilligan** [gemini-testing/gemini#689]
From the `gemini 4.11.3` help output on overwriting config options from the command line:

```
Examples:
      gemini test --browsers-ie8-window-size 1024x768
```

I tried this and it had no effect. I only tried this because I did not manage to set the config that I actually wanted to change: `desiredCapabilities.tunnelIdentifier`. 

Should this be set via `--desired-capabilities-tunnel-identifier FOOBAR` ? This seems ambiguous in that it is unclear which "-" indicates a case switch or a "." to separate key from object.

**Comment by sipayRT** [comment]
it was mistake in example - you should write `--browsers-ie-8-window-size 1024x768`. And you can overwrite only browser options such as `windowSize`, `rootUrl` etc. And you can't overwrite option for `desiredCapabilities` because it's config for grid, not for gemini. If you need different grid configuration you can create new browser for it (for example, chromeMidified) and set it with `-b` option.
