### ISSUE TITLE
Scroll before capturing support

### ISSUE THREAD

**Issue by bruk1977** [gemini-testing/gemini#719]
It would be nice if Gemini supports scrolling to certain pixel/percentage of the page before capturing ... some of the features I'm working on have a visual effect in scroll.

Thanks.

**Comment by DudaGod** [comment]
Hello.

Can you describe your proposal in more details? Why scrolling to the block with selector can't resolve your problem?

How I understand on your page beginning with some pixel - starts a visual effect and you want capture screen after it, am I right? Because if you want capture screen in the process of effect it will be often floating test. I hope you understand it.

**Comment by bruk1977** [comment]
Thanks @DudaGod ... Like scrolling down to lazy load more content and then capture. Because at the page load the component may not be loaded.

**Comment by bruk1977** [comment]
I could achieve this by executing the scroll in before... closing...
