### ISSUE TITLE
DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

### ISSUE THREAD

**Issue by mojoaxel** [gemini-testing/gemini#792]
**gemini@5.0.0-alpha.3**
**npm --version**: 3.10.10
**node version**: v7.3.0

Running gemini with an up-to-date node version results in the following DeprecationWarning:

```sh
DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
```

**Comment by eGavr** [comment]
@mojoaxel, hi!

Thanks for issue.

`os.tmpDir` is called from [wd@0.4.0](https://github.com/admc/wd/blob/v0.4.0/lib/tmp.js#L42) (this package is the dependency of gemini).

Unfortunately, we can not update `wd` to the latest version (update will totally solve the issue), because this package (since 1.0.0) does not support`node@4.x`, but it is vital for our team.

**Comment by mojoaxel** [comment]
I see, thanks anyway!
